TWEAK_NAME = VCamOverlay

VCamOverlay_FILES = VCamOverlayManager.m VCamControlPanel.m VCamColorPicker.m VCamSettings.m
VCamOverlay_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
VCamOverlay_FRAMEWORKS = Foundation CoreFoundation UIKit QuartzCore CoreGraphics IOSurface
VCamOverlay_PRIVATE_FRAMEWORKS =
VCamOverlay_LIBRARIES =

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
